name: Build-Bounce-1.21
on: 
  workflow_dispatch: # Dong nay giup hien nut "Run workflow" de ban bam tay
  push:              # Tu dong build moi khi ban sua code (xoa module)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Permission
        run: chmod +x gradlew

      - name: Run Build
        # Day chinh la lenh tuong duong .\gradlew build tren may ban
        run: ./gradlew build -x test --no-daemon

      - name: Save File Jar
        uses: actions/upload-artifact@v4
        with:
          name: Bounce-1.21-Jar
          path: build/libs/*.jar
